
# Creating a unified customer view from your RudderStack rudder tables;
name: 'dbt_rudderstack_metrics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'rudderstack_analytics'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  dbt_rudderstack_metrics:
    materialized: ephemeral



vars:
  rs_database: 'rudder_autotrack_data'    #This is the name of database where the RudderStack tables are all stored
  rs_schema: 'autotrack'     #This is the name of schema where the RudderStack tables are all stored
  lookback_hours: 48          # This is the duration for which the incremental runs recreate the data. Anything beyond this, the data doesn't change. You can do a full-refresh to force update though.
  session_cutoff_in_sec: 1800           # A session is a continuous sequence of events, as long as the events are within this interval. If two consecutive events occur at an interval of greater than this, a new session is created.
  main_id: anonymous_id
  col_timestamp: "{{timestamp_call('timestamp')}}"
  col_session_id: 'context_session_id'
  col_referrer: 'context_page_referrer'
  col_referring_domain: 'context_page_referring_domain'
  col_utm_source: 'context_campaign_source'
  col_utm_medium: 'context_campaign_medium'

  # All below variables pertain to table names and column names. If the event tracking plan is followed perfectly, it ideally shouldn't need any modifications below.
  
  #table rudder identifies
  tbl_rudder_identifies: "{{ source('rudder', 'identifies') }}"
  col_rudder_identifies_anon_id: 'anonymous_id'
  col_rudder_identifies_user_id: 'user_id'
  col_rudder_identifies_country: 'address_country'
  col_rudder_identifies_timestamp: "{{timestamp_call('timestamp')}}"
  col_rudder_identifies_campaign_source: 'context_campaign_source'
  col_rudder_identifies_device_type: 'context_device_type'
  col_rudder_identifies_device_name: 'context_device_name'
  col_rudder_identifies_device_manufacturer: 'context_device_manufacturer'


  #table rudder tracks
  tbl_rudder_tracks: "{{ source('rudder', 'tracks') }}"
  col_rudder_tracks_anon_id: 'anonymous_id'
  col_rudder_tracks_user_id: 'user_id'
  col_rudder_tracks_timestamp: "{{timestamp_call('timestamp')}}"
  col_rudder_tracks_session_id: 'context_session_id'

  #table rudder pages
  tbl_rudder_pages: "{{ source('rudder', 'pages') }}"
  col_rudder_pages_anon_id: 'anonymous_id'
  col_rudder_pages_user_id: 'user_id'
  col_rudder_pages_timestamp: "{{timestamp_call('timestamp')}}" 
  col_rudder_pages_session_id: 'context_session_id'

  ##table rudder screens
  #tbl_rudder_pages: "{{ source('rudder', 'screens') }}"
  #col_rudder_pages_anon_id: 'anonymous_id'
  #col_rudder_pages_user_id: 'user_id'
  #col_rudder_pages_timestamp: "{{timestamp_call('timestamp')}}" 
  #col_rudder_pages_session_id: 'context_session_id'

